### ISSUE TITLE
502 Bad Gateway after update

### ISSUE THREAD

**Issue by el-schneider** [valeryan/valet-wsl#18]
After installing and using Valet WSL for while without any issues and after a `sudo apt-get upgrade` im getting a **502 Bad Gateway**. I’m not an expert so i have no idea how to fix this.

**Comment by valeryan** [comment]
I would bet that your version of php got upgraded and the custom php config that is added when you do valet install is now in the wrong place. Try running valet install again and it may fix the issue.

**Comment by el-schneider** [comment]
Thanks for your reply!

I tried using different versions of php by `valet use ...`. I did `valet uninstall` and `valet install`. I also removed and required the `valet-wsl` via composer. When i do `valet start` it seems to start the services, but I’m not sure whether they’re really running. How can i check that?

**Comment by valeryan** [comment]
The services are your system services. You can see if PHP and Nginx are running by doing `sudo service --status-all`. However, **502 Bad Gateway** is almost always caused by Nginx not being able to communicate with your PHP-FPM instance. The `valet use` command is not currently working and the WSL system doesn't work well with Unix socks which is how Nginx and Php-fpm normally communicate on a Linux system. 
Valet WSL configures Php and Nginx to use 127.0.0.1:9000 instead of a sock. You may have some leftover configs in `etc/php/{version}/fpm/pool.d/` for the older version of Php that is preventing the current pool to bind that port. Delete any instances of valet.conf you find except for the current version, probably 7.4. 

I am currently working to get the `valet use` command to work and I will add a better cleanup system to handle PHP version upgrades. This is related to #17

**Comment by el-schneider** [comment]
When i do a `--status-all` i cannot see a php service running. So maybe thats the problem?
I followed your other advice and removed valet.conf-files.

**Comment by valeryan** [comment]
Services have to be started through an external method like on the install guide. If you followed the guide you will have a **services.sh** file at `/mnt/c/tools/wsl-startup/`. Make sure the line for starting PHP is set to your current installed version of PHP.

**Comment by el-schneider** [comment]
`sudo service php7.4-fpm start` returns `php7.4-fpm: unrecognized service` although i installed it before. Do you have any idea why this is? Also tried `apt-get remove `and `apt-get install php-7.4-fpm` and it seems to work.

Edit: I guess this was misleading. I wanted to say: the installation seems to work but the service is still missing.

**Comment by valeryan** [comment]
That's weird. maybe just try doing `sudo apt-get install php-fpm` this is a package not just `php-7.4-fpm` it may install the service wrapper maybe.

**Comment by maarten-v** [comment]
I think I know what the problem is. 
By commands like "value use" the file rights of the services can be messed up.
Could you do `ll /etc/init.d`?
I think you will see php7.2-fpm with different file rights then the other files there.
If you type `sudo chmod 755 /etc/init.d/php7.2-fpm` you can startup php again.

**Comment by el-schneider** [comment]
@maarten-v That was the solution. It’s working again. Thank you so much!
@valeryan also thanks to you for your efforts and your time. 
You two are amazing.

**Comment by maarten-v** [comment]
@valeryan  It might be an idea to completely disable the `valet use` function to prevent this from happening?

**Comment by valeryan** [comment]
That is one option. I am looking into the use command to see if I can make it work.

**Comment by guilleagudelo** [comment]
Doing a `valet install` did it for me

**Comment by Chakratos** [comment]
> I think I know what the problem is. By commands like "value use" the file rights of the services can be messed up. Could you do `ll /etc/init.d`? I think you will see php7.2-fpm with different file rights then the other files there. If you type `sudo chmod 755 /etc/init.d/php7.2-fpm` you can startup php again.

Thank you so much! You saved me

**Comment by karemshawky** [comment]
> I think I know what the problem is. By commands like "value use" the file rights of the services can be messed up. Could you do `ll /etc/init.d`? I think you will see php7.2-fpm with different file rights then the other files there. If you type `sudo chmod 755 /etc/init.d/php7.2-fpm` you can startup php again.

This is the right answer 👍
